/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanActionSheet: (typeof import('vant/es'))['ActionSheet']
    VanBadge: (typeof import('vant/es'))['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCalendar: (typeof import('vant/es'))['Calendar']
    VanCell: (typeof import('vant/es'))['Cell']
    VanCellGroup: (typeof import('vant/es'))['CellGroup']
    VanCheckbox: (typeof import('vant/es'))['Checkbox']
    VanCircle: (typeof import('vant/es'))['Circle']
    VanCol: (typeof import('vant/es'))['Col']
    VanDialog: (typeof import('vant/es'))['Dialog']
    VanDivider: (typeof import('vant/es'))['Divider']
    VanEmpty: (typeof import('vant/es'))['Empty']
    VanField: (typeof import('vant/es'))['Field']
    VanForm: (typeof import('vant/es'))['Form']
    VanIcon: (typeof import('vant/es'))['Icon']
    VanImage: (typeof import('vant/es'))['Image']
    VanList: (typeof import('vant/es'))['List']
    VanLoading: (typeof import('vant/es'))['Loading']
    VanOverlay: (typeof import('vant/es'))['Overlay']
    VanPicker: (typeof import('vant/es'))['Picker']
    VanPopup: (typeof import('vant/es'))['Popup']
    VanRow: (typeof import('vant/es'))['Row']
    VanStep: (typeof import('vant/es'))['Step']
    VanStepper: (typeof import('vant/es'))['Stepper']
    VanSteps: (typeof import('vant/es'))['Steps']
    VanSwipeCell: (typeof import('vant/es'))['SwipeCell']
    VanTab: (typeof import('vant/es'))['Tab']
    VanTabs: (typeof import('vant/es'))['Tabs']
  }
}
